### ISSUE TITLE
when() should throw TestoryException instead of NPE if passed value is not proxiable

### ISSUE THREAD

**Issue by mikosik** [testory/testory#85]
Currently following code

```
  private Map<Object, Object> map;

  @Test
  public void test() throws Exception {
    given(map = createMap());
    when(map).size();
    thenReturned(0);
  }

  private ImmutableMap<Object, Object> createMap() {
    return ImmutableMap.of();
  }
```

will fail with NullPointerException at line `when(map).size();` because `when` method returns null when non proxiable object (ImmutableMap from guava library in above case) is passed to it.

In such cases `when` should throw TestoryException (or any other exception) to indicate that testory framework has been used incorrectly instead of misleading user into thinking that `map` value is null. Otherwise my initial thought is to go and check implementation of `createMap` to see why it returned null.

reproduced on testory-1.0.0

**Comment by maciejmikosik** [comment]
Testory cannot know in advance if test uses `when` in chained form.
Preventing non proxiable objects inside `when` would make following test fail with `TestoryException`.

    when(createMap());
    thenReturned(instanceOf(Map.class));
